// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android =  FirebaseOptions(
    apiKey: 'AIzaSyDFPWVyDPxiqtRgU-gGDgtE-toADeyn1OY',
    appId: '1:310804058293:android:e24e0f05b92927a2f3aefc',
    messagingSenderId: '310804058293',
    projectId: 'mynotes-flutterfire-app',
    storageBucket: 'mynotes-flutterfire-app.appspot.com',
  );

  static const FirebaseOptions ios =  FirebaseOptions(
    apiKey: 'AIzaSyDJDrTj75F1eStmW8V7i-6_aaKegyttLAU',
    appId: '1:310804058293:ios:c959f5219923713ef3aefc',
    messagingSenderId: '310804058293',
    projectId: 'mynotes-flutterfire-app',
    storageBucket: 'mynotes-flutterfire-app.appspot.com',
    iosClientId: '310804058293-jspl3boslp47h4064217la35nhcmucmb.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
